---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: quote-route
  namespace: quote
spec:
  http:
    - name: quote
      match:
        hosts: 
          - quote.glegal.local
        paths:
          - /*

      backends:
        - serviceName: quote
          servicePort: 80
          # resolveGranularity: service

