---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: quote-route
  namespace: quote
spec:
  http:
    - name: quote
      match:
        paths:
          - /quote*
      plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/quote(/|$)(.*)", "/$2"]
      - name: redirect
        enable: true
        config:
          regex_uri: ["^(/quote)$", "$1/"]
      # - name: redirect
      #   enable: true
      #   config:
      #     http_to_https: true
      backends:
        - serviceName: quote
          servicePort: 80
          # resolveGranularity: service
