---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: quote
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    # - name: https
    #   port: 443
    #   targetPort: 8000
  type: ClusterIP
  selector:
    app: quote
