apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-apisix
resources:
  - namespace.yaml
  - externalsecret.yaml
  - release.yaml

configMapGenerator:
  - name: base-values
    files:
      - values.yaml=values-base.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: apisix-admin-local-secret
#     literals:
#       - admin.credentials.admin=11111111111
configurations:
  - kustomizeconfig.yaml
