apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-apisix
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: base-values
    files:
      - values.yaml=values-base.yaml
configurations:
  - kustomizeconfig.yaml
