apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: grafana-credentials-ext
  data:
    - secretKey: admin-user
      remoteRef:
        key: GRAFANA_ADMIN
    - secretKey: admin-password
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
