apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apisix-admin-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: apisix-admin-secret
  data:
    - secretKey: admin
      remoteRef:
        key: APISIX_ADMIN_TOKEN

