apiVersion: v1
kind: Service
metadata:
  name: storage-groupprovider
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: 9160
      protocol: TCP
  selector:
    app: storage-groupprovider
