apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: web
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: web
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["web", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: WEB_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: WEB_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: WEB_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: WEB_HTTP_ADDR
              value: 0.0.0.0:9100

            - name: WEB_OIDC_AUTHORITY
              value: "https://{{ $.Values.externalDomain }}"
            - name: WEB_UI_THEME_SERVER
              value: "https://{{ $.Values.externalDomain }}"
            - name: WEB_UI_CONFIG_SERVER
              value: "https://{{ $.Values.externalDomain }}"
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9100
