apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret-example
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: aws-credentials
  data:
    - secretKey: aws_secret_access_key
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
    - secretKey: aws_access_key_id
      remoteRef:
        key: AWS_ACCESS_KEY_ID
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: example
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: fake
#     kind: ClusterSecretStore
#   target:
#     name: secret-to-be-created
#   data:
#     - secretKey: foo_bar
#       remoteRef:
#         key: /foo/bar
#         version: v1
#   dataFrom:
#     - extract:
#         key: /foo/baz
