apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-userprovider
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-userprovider
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-userprovider
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: storage-userprovider
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-userprovider", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_USERPROVIDER_ADDR
              value: 0.0.0.0:9144
            - name: STORAGE_USERPROVIDER_ENDPOINT
              value: "storage-userprovider:9144"

            - name: STORAGE_USERPROVIDER_DRIVER
              value: "ldap"
            - name: STORAGE_LDAP_HOSTNAME
              value: "glauth"
            - name: STORAGE_LDAP_PORT
              value: "9126"
            - name: STORAGE_LDAP_INSECURE # TODO: https://github.com/owncloud/ocis-charts/issues/32
              value: "true"

            - name: STORAGE_LDAP_IDP
              value: "https://{{ $.Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          envFrom:
            - secretRef:
                name: jwt-secret
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9144
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
