---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  http:
    - name: dashboard
      match:
        hosts:
          - grafana.glegal.local
        paths:
          - /*
      backends:
        - serviceName: grafana
          servicePort: 3000
          # resolveGranularity: service
