apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-gateway
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-gateway
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-gateway
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: storage-gateway
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-gateway", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_GATEWAY_GRPC_ADDR
              value: 0.0.0.0:9142
            - name: REVA_GATEWAY
              value: storage-gateway:9142

            - name: STORAGE_FRONTEND_PUBLIC_URL
              value: "https://{{ $.Values.externalDomain }}"

            - name: STORAGE_USERS_ENDPOINT
              value: "storage-users:9157"

            - name: STORAGE_PUBLIC_LINK_ENDPOINT
              value: "storage-publiclink:9178"

            - name: STORAGE_AUTH_BASIC_ENDPOINT
              value: "storage-authbasic:9146"
            - name: STORAGE_AUTH_BEARER_ENDPOINT
              value: "storage-authbearer:9166"
            - name: STORAGE_AUTH_MACHINE_ENDPOINT
              value: "storage-authmachine:9148"

            - name: STORAGE_SHARES_ENDPOINT
              value: "storage-shares:9154"
            - name: STORAGE_SHARING_ENDPOINT
              value: "storage-sharing:9150"

            - name: STORAGE_GROUPPROVIDER_ENDPOINT
              value: "storage-groupprovider:9160"
            - name: STORAGE_USERPROVIDER_ENDPOINT
              value: "storage-userprovider:9144"
            - name: STORAGE_PERMISSIONS_ENDPOINT
              value: "settings:9191"
          envFrom:
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: transfer-secret
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9142
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
