---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-cert
spec:
  dnsNames:
    - helloweb.glegal.local
  issuerRef:
    name: global-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: hello-cert
  commonName: example.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  duration: 2h 
  renewBefore: 50m
  subject:
    organizations:
      - GLEGAL
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: hello-tls
spec:
  hosts:
    - helloweb.glegal.local
  secret:
    name: hello-cert # the secret created by cert-manager
    namespace: default # secret namespace