---
apiVersion: v1
kind: Secret
metadata:
  name: transfer-secret
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
type: Opaque
data:
    # TODO: create random default value when no value is set in values.yaml https://github.com/owncloud/ocis-charts/issues/9
    STORAGE_TRANSFER_SECRET: "{{ b64enc $.Values.secrets.transfer }}"
