apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuiper
  namespace: emqx
spec:
  releaseName: kuiper
  chart:
    spec:
      chart: kuiper
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
