---
apiVersion: v1
kind: Secret
metadata:
  name: thumbnails-transfer-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
type: Opaque
data:
    # TODO: create random default value when no value is set in values.yaml https://github.com/owncloud/ocis-charts/issues/9
    THUMBNAILS_TRANSFER_TOKEN: "{{ b64enc $.Values.secrets.jwt }}"
