apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/12
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: nats
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: nats
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["nats-server", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: NATS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: NATS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: NATS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: NATS_NATS_HOST
              value: "0.0.0.0"
            - name: NATS_NATS_PORT
              value: "9233"
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: nats
              containerPort: 9233
