apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: proxy
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: proxy
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      #hostAliases:
      #  - ip: "127.0.0.1"
      #    hostnames:
      #      - "{{ $.Values.externalDomain }}"
      containers:
        #- name: idp-hack-sidecar
        #  image: alpine/socat
        #  args: ["tcp-l:443,fork,reuseaddr", "tcp:127.0.0.1:9200"]
        - name: proxy
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["proxy", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: PROXY_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: PROXY_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: PROXY_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: PROXY_HTTP_ADDR
              value: 0.0.0.0:9200
            - name: PROXY_AUTOPROVISION_ACCOUNTS
              value: "true"
            - name: PROXY_ENABLE_BASIC_AUTH
              value: "true"
            - name: PROXY_OIDC_ISSUER
              value: "https://{{ $.Values.externalDomain }}"
            - name: PROXY_TLS
              value: "false"

            - name: PROXY_OIDC_INSECURE # TODO: https://github.com/owncloud/ocis-charts/issues/32
              value: "true"
            - name: PROXY_INSECURE_BACKENDS
              value: "false"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          envFrom:
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: machine-auth-api-key
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9200
          volumeMounts:
            - name: configs
              mountPath: /etc/ocis
      volumes:
        - name: configs
          configMap:
            name: proxy-config
