apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  releaseName: emqx
  chart:
    spec:
      chart: emqx
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
    replicaCount: 1
