apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-sharing
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-sharing
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/12
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-sharing
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      {{- if $.Values.storageSharing.persistence.enabled }}
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "1000:1000", "/var/lib/ocis"]
          volumeMounts:
          - name: storage-sharing-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: storage-sharing
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-sharing", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_SHARING_GRPC_ADDR
              value: 0.0.0.0:9150
            - name: STORAGE_SHARING_ENDPOINT
              value: 'storage-users:9150'

            - name: STORAGE_USERS_HTTP_ADDR
              value: 0.0.0.0:9158
            - name: STORAGE_USERS_DATA_SERVER_URL
              value: "http://storage-users:9158/data"

            - name: STORAGE_SHARING_USER_DRIVER
              value: "json"
            - name: STORAGE_SHARING_PUBLIC_DRIVER
              value: "json"

            - name: STORAGE_SHARING_EVENTS_ADDRESS
              value: nats:9233

            - name: REVA_GATEWAY
              value: "storage-gateway:9142"
          envFrom:
            - secretRef:
                name: jwt-secret
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9150
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: storage-sharing-data
              mountPath: /var/lib/ocis
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
      {{- if $.Values.storageSharing.persistence.enabled }}
        - name: storage-sharing-data
          persistentVolumeClaim:
            claimName: storage-sharing-data
      {{ else }}
        - name: storage-sharing-data
          emptyDir: {}
      {{ end }}
