apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credential-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: aws-credentials
  data:
    - secretKey: aws_secret_access_key
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
    - secretKey: aws_access_key_id
      remoteRef:
        key: AWS_ACCESS_KEY_ID
