---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./releases/download/v1.8.0/cert-manager.crds.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
