---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-crds
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/certs/crs
  prune: true
