apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: release-1.8
  url: http://github.com/cert-manager/cert-manager
