apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnails
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: thumbnails
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: thumbnails
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      {{- if $.Values.thumbnails.persistence.enabled }}
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "1000:1000", "/var/lib/ocis"]
          volumeMounts:
          - name: thumbnails-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: thumbnails
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["thumbnails", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: THUMBNAILS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: THUMBNAILS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: THUMBNAILS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: THUMBNAILS_GRPC_ADDR
              value: 0.0.0.0:9185
            - name: THUMBNAILS_HTTP_ADDR
              value: 0.0.0.0:9186

            - name: THUMBNAILS_DATA_ENDPOINT
              value: http://thumbnails:9186/thumbnails/data

            - name: THUMBNAILS_CS3SOURCE_INSECURE # TODO: https://github.com/owncloud/ocis-charts/issues/32
              value: "true"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          envFrom:
            - secretRef:
                name: thumbnails-transfer-secret
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9185
            - name: http
              containerPort: 9186
          volumeMounts:
            - name: thumbnails-data
              mountPath: /var/lib/ocis
      volumes:
      {{- if $.Values.thumbnails.persistence.enabled }}
        - name: thumbnails-data
          persistentVolumeClaim:
            claimName: thumbnails-data
      {{ else }}
        - name: thumbnails-data
          emptyDir: {}
      {{ end }}
