apiVersion: v1
kind: Service
metadata:
  name: thumbnails
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: 9185
      protocol: TCP
    - name: http
      port: 9186
      protocol: TCP
  selector:
    app: thumbnails
