apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-metadata
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-metadata
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/12
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-metadata
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      {{- if $.Values.storageMetadata.persistence.enabled }}
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "1000:1000", "/var/lib/ocis"]
          volumeMounts:
          - name: storage-metadata-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: storage-metadata
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-metadata", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            # logging
            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            # external availability grpc
            - name: STORAGE_METADATA_GRPC_ADDR
              value: 0.0.0.0:9215

            # external availability data gateway
            - name: STORAGE_METADATA_HTTP_ADDR
              value: 0.0.0.0:9216
            - name: STORAGE_METADATA_DATA_SERVER_URL
              value: "http://storage-metadata:9216/data"

            # data gateway
            - name: STORAGE_METADATA_DATAPROVIDER_INSECURE # TODO: https://github.com/owncloud/ocis-charts/issues/32
              value: "true"

            # oCIS storage driver (decomposed filesystem)
            - name: STORAGE_METADATA_DRIVER
              value: "ocis"

            # permissions middleware
            - name: STORAGE_PERMISSIONS_ENDPOINT
              value: "settings:9191"
            - name: REVA_GATEWAY
              value: "storage-gateway:9142"
          envFrom:
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: transfer-secret
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9215
            - name: http
              containerPort: 9216
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: storage-metadata-data
              mountPath: /var/lib/ocis
      volumes:
        - name: tmp-volume
          emptyDir:
              medium: Memory
              sizeLimit: 6Mi
      {{- if $.Values.storageMetadata.persistence.enabled }}
        - name: storage-metadata-data
          persistentVolumeClaim:
            claimName: storage-metadata-data
      {{ else }}
        - name: storage-metadata-data
          emptyDir: {}
      {{ end }}
