apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: settings
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: settings
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: settings
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["settings", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: SETTINGS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: SETTINGS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: SETTINGS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: SETTINGS_HTTP_ADDR
              value: 0.0.0.0:9190
            - name: SETTINGS_GRPC_ADDR
              value: 0.0.0.0:9191

            - name: SETTINGS_STORE_TYPE
              value: metadata
            - name: STORAGE_GATEWAY_GRPC_ADDR
              value: storage-gateway:9142
            - name: STORAGE_GRPC_ADDR
              value: storage-metadata:9215
            - name: METADATA_SERVICE_USER_IDP # TODO: https://github.com/owncloud/ocis-charts/issues/35
              value: "https://{{ $.Values.externalDomain }}"
          envFrom:
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: machine-auth-api-key
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9190
            - name: grpc
              containerPort: 9191
