apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix-ingress-controller
spec:
  releaseName: apisix-ingress-controller
  chart:
    spec:
      chart: apisix-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: apiseven
        namespace: flux-system
      version: "0.9.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: base-values
  #     # valuesKey: values-base.yaml
  #     optional: false
  values:
    apisix:
      serviceName: apisix-admin
      serviceNamespace: ingress-apisix
      servicePort: 9180
      adminKey: "2e249deb-bd15-48e9-8599-e01b2aeda77f"
      clusterName: "default"
