apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-apisix

resources:
  - ../../base/apisix
  - ingress.yaml
patchesStrategicMerge:
  - local-values.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: apisix-admin-local-secret
#     literals:
#       - admin.credentials.admin=11111111111
