apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix
spec:
  releaseName: apisix
  chart:
    spec:
      chart: apisix
      sourceRef:
        kind: HelmRepository
        name: apiseven
        namespace: flux-system
      # version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    admin:
      credentials:
        admin: 1111111111
