apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix
spec:
  releaseName: apisix
  chart:
    spec:
      chart: apisix
      sourceRef:
        kind: HelmRepository
        name: apiseven
        namespace: flux-system
      # version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingress-controller:
      enabled: false
    # admin:
    #   credentials:
    #     admin: 2e249deb-bd15-48e9-8599-e01b2aeda77f
