apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
  namespace: ocis
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocis-cert
  namespace: ocis
spec:
  dnsNames:
    - ocis.glegal.local
  issuerRef:
    kind: Issuer
    name: issuer
  secretName: ocis-cert
  usages:
    - digital signature
    - key encipherment
  # renewBefore: 0h55m0s
  # duration: 1h0m0s
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: httpserver-route
  namespace: ocis
spec:
  http:
    - name: ocis
      match:
        hosts:
          - ocis.glegal.local
        paths:
          - "/*"
      backends:
        - serviceName: proxy
          servicePort: 9200
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixTls
metadata:
  name: ocis-tls
  namespace: ocis
spec:
  hosts:
    - ocis.glegal.local
  secret:
    name: ocis-cert # the secret created by cert-manager
    namespace: ocis # secret namespace