apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

# commonLabels:
#   app: ocis

# namespace: ocis

resources:
  - namespace.yaml
  - certificate.yaml
  # - all.yaml
  # - ocis_2.yaml
  - ocis_3.yaml

# helmCharts:
# - name: metallb
#   # valuesInline:
#   #   existingConfigMap: "test-config"
#   # includeCRDs: true
#   repo: https://github.com/owncloud/ocis-charts
#   releaseName: ocis
#   namespace: ocis

# secretGenerator:
# - name: jwt-secret
#   literals:
#   - OCIS_JWT_SECRET="cippalippa"
# - name: transfer-secret
#   literals:
#   - STORAGE_TRANSFER_SECRET="cippalippa"
# - name: machine-auth-api-key
#   literals:
#   - OCIS_MACHINE_AUTH_API_KEY="cippalippa"
# - name: thumbnails-transfer-secret
#   literals:
#   - THUMBNAILS_TRANSFER_TOKEN="cippalippa"

  
