externalDomain: ocis.glegal.local:8443

ingress:
  enabled: true
  ingressClassName: apisix
  annotations:
    # kubernetes.io/ingress.class: apisix
    kubernetes.io/tls-acme: "true"
  labels: {}

  tls:
    - secretName: example-cert
      hosts:
        - ocis.glegal.local

storageMetadata:
  persistence:
    enabled: false
    # storageClassName: default
    accessModes:
      - ReadWriteMany
    size: 1Gi
    annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    selectorLabels: {}
    # existingClaim:

storageSharing:
  persistence:
    enabled: false
    # storageClassName: default
    accessModes:
      - ReadWriteMany
    size: 1Gi
    annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    selectorLabels: {}
    # existingClaim:

storageUsers:
  storageBackend:
    driver: ocis # stores all data in the persistent volume if persistence is enabled
    # driver: s3ng # stores all metadata in the persistent volume and uploads blobs to s3 if persistence is enabled
    # driverConfig:
    #   s3ng:
    #     endpoint: https://localhost:1234
    #     region: default
    #     bucket: example-bucket
    #     accessKey: lorem-ipsum
    #     secretKey: lorem-ipsum
  persistence:
    enabled: false
    # storageClassName: default
    accessModes:
      - ReadWriteMany
    size: 50Gi
    annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    selectorLabels: {}
    # existingClaim:

store:
  persistence:
    enabled: false
    # storageClassName: default
    accessModes:
      - ReadWriteMany
    size: 1Gi
    annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    selectorLabels: {}
    # existingClaim:

thumbnails:
  persistence:
    enabled: false
    # storageClassName: default
    accessModes:
      - ReadWriteMany
    size: 2Gi
    annotations: {}
    finalizers: []
    selectorLabels: {}
    # existingClaim:
