apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: idp
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/12
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: idp
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: idp
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["idp", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: IDP_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: IDP_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: IDP_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: IDP_HTTP_ADDR
              value: 0.0.0.0:9130

            - name: IDP_ISS
              value: "https://{{ $.Values.externalDomain }}"

            - name: IDP_LDAP_URI
              value: ldap://glauth:9125
            - name : IDP_INSECURE #TODO: https://github.com/owncloud/ocis-charts/issues/32
              value: "true"
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9130
