---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: quote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: quote
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: backend
          image: docker.io/datawire/quote:0.5.0
          ports:
            - name: http
              containerPort: 8080
