apiVersion: v1
kind: Service
metadata:
  name: settings
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: 9191
      protocol: TCP
    - name: http
      port: 9190
      protocol: TCP
  selector:
    app: settings
