apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: taosdata
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/taosdata/TDengine-Operator
  ref:
    branch: "3.0"
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/
