apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdengine
  namespace: tdengine
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/tdengine-0.3.0.tgz
      sourceRef:
        kind: GitRepository
        name: taosdata
        namespace: flux-system
      interval: 1m
  values:
    image:
      prefix: tdengine/tdengine
      tag: "2.4.0.18"
    storage:
      className: "local-path"
      dataSize: "3Gi"
      logSize: "1Gi"
    timezone: "Europe/Rome"
